api_branch: origin/master
api_parser: ~
api_cfgmod: clone
api_runner: ~
api_paths: lib
env_make: ~
env_prep: composer-get
php_conf: timezone
php_exts: ~
app_prep: composer-req
app_post: ~
env_post: composer-del,ci-coveralls,ci-codacy
app_path: ~
pkg_name: vermicious-console-io-library
pkg_desc: "Enhanced console input/output style implementation with a complete object-oriented API."
pkg_bndl: false
